default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  username: rails

development:
  <<: *default
  database: paintball_develop
  password: oSgRNFVn1Y

test:
  <<: *default
  database: paintball_test
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: paintball_production
  database: <%= ENV['APP_DATABASE_PASSWORD'] %>
